name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - name: Deploy Dengan SSH
        uses: ssh
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script:
            cd ~/var/www/testing.cicd
            git pull origin mian
            git status